"""
Phase 2 tests: the PostgreSQL schema and query layer, tested in isolation
before FastAPI or the agent exist (per the phase plan).

Requires:
  - sql/schema.sql applied to a running Postgres instance
  - scripts/load_postgres.py --truncate already run against it
  - DATABASE_URL set (see .env.example)

These assert against KNOWN GROUND TRUTH from the six injected failure
scenarios (see spark_jobs/config.py SCENARIOS), not generic sanity checks —
consistent with how Phase 1's test suite was built.
"""

from __future__ import annotations

import os
from datetime import datetime

import pytest
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

from app.core.tenancy import DEFAULT_TENANT_ID as T
from app.database.queries import (
    get_ai4i_failure_mode_rates,
    get_fleet_status,
    get_machine,
    get_machine_anomalies,
    get_machine_health,
    get_maintenance_records,
    get_sensor_summary,
    list_machines,
    rank_machines_for_inspection,
)

load_dotenv()

SCENARIO_MACHINES = {"M-01", "M-02", "M-03", "M-04", "M-05", "M-06"}
SUSTAINED_SCENARIO_MACHINES = {"M-01", "M-02", "M-03", "M-04", "M-06"}  # excludes M-05's one-off blip
HEALTHY_MACHINES = {f"M-{i:02d}" for i in range(7, 19)}


@pytest.fixture(scope="module")
def engine():
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        pytest.skip("DATABASE_URL not set")
    return create_engine(database_url)


@pytest.fixture()
def conn(engine):
    with engine.connect() as connection:
        yield connection


# ---------------------------------------------------------------------
# Row counts / referential integrity
# ---------------------------------------------------------------------

def test_row_counts_match_pipeline_output(conn):
    counts = {
        row[0]: row[1]
        for row in conn.execute(text("""
            SELECT 'machines', COUNT(*) FROM machines
            UNION ALL SELECT 'sensor_summary', COUNT(*) FROM sensor_summary
            UNION ALL SELECT 'machine_anomalies', COUNT(*) FROM machine_anomalies
            UNION ALL SELECT 'maintenance_records', COUNT(*) FROM maintenance_records
            UNION ALL SELECT 'ai4i_reference', COUNT(*) FROM ai4i_reference
        """)).fetchall()
    }
    assert counts["machines"] == 18
    assert counts["sensor_summary"] == 25920  # 18 machines x 1440 hourly windows
    # Audit F9: was 18,912 before the rolling-window fix (z-score
    # baseline previously included the point being tested, which
    # mathematically capped the z-score just above the anomaly threshold
    # and made the statistical layer almost inert). With the fix,
    # 28,855 rows is the real count from a re-run of the pipeline
    # against this same data (verified: HIGH severity rows went from 16
    # to 248 in the same re-run — the statistical layer now actually
    # contributes signal instead of noise).
    assert counts["machine_anomalies"] == 28855
    assert counts["maintenance_records"] == 7
    assert counts["ai4i_reference"] == 10000


def test_no_orphaned_foreign_keys(conn):
    """Every child-table machine_id must exist in machines — the FK
    constraints enforce this at write time, but confirm it holds for data
    that was already loaded via a bulk path that could bypass checks."""
    for table in ["sensor_summary", "machine_anomalies", "maintenance_records"]:
        orphans = conn.execute(text(f"""
            SELECT COUNT(*) FROM {table} t
            LEFT JOIN machines m
              ON m.tenant_id = t.tenant_id AND m.machine_id = t.machine_id
            WHERE m.machine_id IS NULL
        """)).scalar()
        assert orphans == 0, f"{table} has rows with no matching machine"


# ---------------------------------------------------------------------
# list_machines / get_machine
# ---------------------------------------------------------------------

def test_list_machines_returns_all_18(conn):
    machines = list_machines(conn, tenant_id=T)
    assert len(machines) == 18
    assert {m["machine_id"] for m in machines} == SCENARIO_MACHINES | HEALTHY_MACHINES


def test_get_machine_unpopulated_fields_are_null_not_fabricated(conn):
    """name/install_date/location were never generated by Phase 1 — confirm
    they're genuinely NULL, not silently defaulted to something invented."""
    machine = get_machine(conn, "M-01", tenant_id=T)
    assert machine is not None
    assert machine["name"] is None
    assert machine["install_date"] is None
    assert machine["location"] is None
    assert machine["production_line"] == "LINE-1"


def test_get_machine_unknown_id_returns_none(conn):
    assert get_machine(conn, "M-99", tenant_id=T) is None


# ---------------------------------------------------------------------
# get_machine_health / get_fleet_status
# ---------------------------------------------------------------------

def test_m04_unresolved_osf_shows_non_healthy_at_end_of_period(conn):
    """M-04 has an OSF scenario with no repair — the last recorded window
    should reflect that, not read as HEALTHY."""
    health = get_machine_health(conn, "M-04", tenant_id=T)
    assert health is not None
    assert health["health_status"] in ("WATCH", "AT_RISK")


def test_fleet_status_covers_every_machine_once(conn):
    status = get_fleet_status(conn, tenant_id=T)
    assert len(status) == 18
    assert {s["machine_id"] for s in status} == SCENARIO_MACHINES | HEALTHY_MACHINES


# ---------------------------------------------------------------------
# rank_machines_for_inspection — the deterministic "inspect first" ranking
# ---------------------------------------------------------------------

def test_ranking_surfaces_sustained_scenario_machines_above_healthy_baseline(conn):
    """The 5 machines with sustained injected failures should dominate the
    top of the ranking over the whole simulation period. This is the same
    result already verified in Phase 1 (anomalous_reading_count), now
    reached via the actual SQL query the agent's tool will call."""
    ranked = rank_machines_for_inspection(conn, since=datetime(2026, 1, 1), top_n=5, tenant_id=T)
    ranked_ids = {r["machine_id"] for r in ranked}
    assert ranked_ids == SUSTAINED_SCENARIO_MACHINES
    # rank_machines_for_inspection orders by high_severity_count first,
    # anomaly_count second (see its own docstring/SQL) — not raw volume.
    # Before audit F9's rolling-window fix, HIGH severity was 16 rows
    # fleet-wide and effectively noise, so M-04's raw anomaly volume
    # happened to win. With the fix, M-06 (TWF_RECURRING: two separate
    # onset/repair cycles, each an acute transition) legitimately
    # accumulates more HIGH-severity flags than M-04 (OSF: one sustained
    # but comparatively gradual degradation) — a real, more meaningful
    # ranking now that severity carries signal instead of noise.
    assert ranked[0]["machine_id"] == "M-06"


def test_m05_oneoff_blip_does_not_stand_out_in_aggregate_ranking(conn):
    """M-05's single RNF blip is deliberately NOT supposed to separate from
    healthy noise in an aggregate count — that's honest behavior, not a
    bug (see Phase 1 notes). Confirm its total anomaly count sits inside
    the healthy machines' range, not near the sustained-scenario machines."""
    healthy_counts = [
        row[0]
        for row in conn.execute(text("""
            SELECT COUNT(*) FROM machine_anomalies
            WHERE machine_id = ANY(:ids) GROUP BY machine_id
        """), {"ids": list(HEALTHY_MACHINES)}).fetchall()
    ]
    m05_count = conn.execute(
        text("SELECT COUNT(*) FROM machine_anomalies WHERE machine_id = 'M-05'")
    ).scalar()
    assert min(healthy_counts) <= m05_count <= max(healthy_counts) * 1.1


def test_m05_blip_is_caught_at_its_exact_injected_timestamp(conn):
    """Even though M-05 doesn't stand out in aggregate, the per-event
    query must still catch the blip at its actual injected onset
    (day 40 -> 2026-02-09/10). This is the "only per-event inspection
    catches it" claim from Phase 1, verified against the real DB."""
    events = get_machine_anomalies(
        conn, "M-05", since=datetime(2026, 2, 9), severity="HIGH", tenant_id=T
    )
    assert len(events) >= 1
    assert any(e["detected_at"].date() in (datetime(2026, 2, 9).date(), datetime(2026, 2, 10).date()) for e in events)


# ---------------------------------------------------------------------
# get_maintenance_records — recurring vs. one-time vs. unresolved
# ---------------------------------------------------------------------

def test_m06_has_two_maintenance_episodes(conn):
    """M-06 has a recurring TWF scenario (two separate repair events) —
    confirms 'has this happened before' queries have real data to find."""
    records = get_maintenance_records(conn, "M-06", tenant_id=T)
    assert len(records) == 2
    assert all(r["resolved"] for r in records)


def test_m04_maintenance_record_is_unresolved(conn):
    records = get_maintenance_records(conn, "M-04", tenant_id=T)
    assert len(records) == 1
    assert records[0]["resolved"] is False


def test_healthy_machine_has_no_maintenance_records(conn):
    assert get_maintenance_records(conn, "M-10", tenant_id=T) == []


# ---------------------------------------------------------------------
# get_sensor_summary — ordering and filtering
# ---------------------------------------------------------------------

def test_sensor_summary_is_most_recent_first_and_respects_limit(conn):
    rows = get_sensor_summary(conn, "M-01", limit=5, tenant_id=T)
    assert len(rows) == 5
    starts = [r["window_start"] for r in rows]
    assert starts == sorted(starts, reverse=True)


def test_sensor_summary_since_filter_excludes_earlier_windows(conn):
    cutoff = datetime(2026, 2, 1)
    rows = get_sensor_summary(
        conn, "M-01", since=cutoff, limit=10000, tenant_id=T)
    assert all(r["window_start"] >= cutoff for r in rows)


# ---------------------------------------------------------------------
# get_ai4i_failure_mode_rates — P2 cleanup, real UCI AI4I dataset context
# ---------------------------------------------------------------------

def test_ai4i_failure_mode_rates_covers_all_five_modes(conn):
    """No hardcoded expected percentages here — those are a fact about
    the real published dataset, not this project's code — just the
    invariants get_ai4i_failure_mode_rates promises: all five AI4I codes
    present, rates bounded, and every mode's total_real_failures agrees
    (it's the same denominator query run once per mode)."""
    rates = get_ai4i_failure_mode_rates(conn)
    assert set(rates) == {"TWF", "HDF", "PWF", "OSF", "RNF"}
    total_failures = {stats["total_real_failures"] for stats in rates.values()}
    assert len(total_failures) == 1  # same denominator across all five modes
    for mode, stats in rates.items():
        assert stats["total_real_rows"] == 10000
        assert 0 <= stats["failure_count"] <= stats["total_real_failures"]
        assert 0 <= stats["share_of_real_failures"] <= 1


# ---------------------------------------------------------------------
# Index sanity check — confirm the planned composite index is actually
# used for the query pattern it was built for, not just present.
# ---------------------------------------------------------------------

def test_machine_window_query_uses_the_composite_index(conn):
    plan = conn.execute(text("""
        EXPLAIN SELECT * FROM sensor_summary
        WHERE tenant_id = 'default' AND machine_id = 'M-01'
          AND window_start >= '2026-02-01'
        ORDER BY window_start DESC LIMIT 10
    """)).fetchall()
    plan_text = "\n".join(row[0] for row in plan)
    # Postgres may plan this via the named idx_sensor_summary_machine_window
    # OR via the UNIQUE (tenant_id, machine_id, window_start) constraint's
    # own auto-created index — both cover the same three columns in the same
    # order, so either is the composite index doing its job (a sequential
    # scan is the failure mode this test guards against).
    assert "Index Scan" in plan_text
    assert "sensor_summary" in plan_text
    assert "Seq Scan" not in plan_text
