"""Uploads, background jobs and rejected rows (Phase 3 of the self-serve platform).

  * uploads        - one row per file a tenant uploaded. The object key is
    generated by the server (tenants/<tenant_id>/uploads/<upload_id>/data.csv)
    and the confirmed column mapping is stored on the row (the older
    tenant_schema_mappings CHECK only allows 'operational'/'maintenance').
  * jobs           - the work queue AND its status. A Postgres-backed queue:
    workers claim rows with FOR UPDATE SKIP LOCKED through the SECURITY
    DEFINER function iia_claim_job() (cross-tenant by design; it returns only
    ids), then do everything else with the tenant context bound.
  * rejected_rows  - rows/cells a job refused, with a reason and the raw row.
  * RLS            - uploads and rejected_rows are FORCEd like every other
    tenant table. `jobs` is ENABLEd but not FORCEd: the claim/reap functions
    run as the table owner and must see every tenant's jobs; iia_app and
    iia_worker are not owners, so the tenant_isolation policy still binds them.
  * iia_worker     - a second least-privilege role (NOLOGIN here;
    scripts/provision_app_role.py sets LOGIN from WORKER_DB_PASSWORD). It gets
    the write grants the worker needs; iia_app stays read-mostly. Both roles'
    grants are (re)applied by iia_grant_app_privileges(), so restore_db.py
    needs no change.
  * machine_anomalies gets UNIQUE (tenant_id, machine_id, detected_at). Without
    it, re-running the same upload would insert every anomaly again. The
    upgrade refuses (with the offending count) if existing rows already
    violate it.
  * machines.production_line widens VARCHAR(20) -> VARCHAR(100): the mapping
    accepts any string there. (machine_id was already widened by 0005.)

Revision ID: 0007
Revises: 0006
"""
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None

_NOW = "(NOW() AT TIME ZONE 'UTC')"

_TABLES = f"""
CREATE TABLE uploads (
    upload_id     UUID         PRIMARY KEY,
    tenant_id     VARCHAR(48)  NOT NULL REFERENCES tenants(tenant_id),
    filename      VARCHAR(255) NOT NULL,
    content_type  VARCHAR(100) NOT NULL,
    storage_key   VARCHAR(300) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'created'
                  CHECK (status IN ('created', 'uploaded', 'mapped')),
    size_bytes    BIGINT,
    sha256        CHAR(64),
    mapping       JSONB,
    created_at    TIMESTAMP    NOT NULL DEFAULT {_NOW},
    updated_at    TIMESTAMP    NOT NULL DEFAULT {_NOW},
    UNIQUE (tenant_id, upload_id)
);
CREATE INDEX idx_uploads_tenant_created ON uploads (tenant_id, created_at);

CREATE TABLE jobs (
    job_id         UUID         PRIMARY KEY,
    tenant_id      VARCHAR(48)  NOT NULL REFERENCES tenants(tenant_id),
    upload_id      UUID         NOT NULL,
    type           VARCHAR(30)  NOT NULL DEFAULT 'sensor_ingest' CHECK (type IN ('sensor_ingest')),
    status         VARCHAR(20)  NOT NULL DEFAULT 'queued'
                   CHECK (status IN ('queued', 'running', 'succeeded', 'failed')),
    stage          VARCHAR(20),
    created_at     TIMESTAMP    NOT NULL DEFAULT {_NOW},
    started_at     TIMESTAMP,
    finished_at    TIMESTAMP,
    locked_at      TIMESTAMP,
    run_after      TIMESTAMP    NOT NULL DEFAULT {_NOW},
    rows_in        BIGINT       NOT NULL DEFAULT 0,
    rows_loaded    BIGINT       NOT NULL DEFAULT 0,
    rows_rejected  BIGINT       NOT NULL DEFAULT 0,
    error          TEXT,
    retry_count    INTEGER      NOT NULL DEFAULT 0,
    max_retries    INTEGER      NOT NULL DEFAULT 3,
    UNIQUE (tenant_id, job_id),
    FOREIGN KEY (tenant_id, upload_id) REFERENCES uploads (tenant_id, upload_id)
);
CREATE INDEX idx_jobs_tenant_created ON jobs (tenant_id, created_at);
CREATE INDEX idx_jobs_queue ON jobs (run_after) WHERE status = 'queued';

CREATE TABLE rejected_rows (
    id          BIGSERIAL    PRIMARY KEY,
    tenant_id   VARCHAR(48)  NOT NULL REFERENCES tenants(tenant_id),
    job_id      UUID         NOT NULL,
    row_number  INTEGER,
    code        VARCHAR(40)  NOT NULL,
    reason      TEXT         NOT NULL,
    raw         JSONB,
    FOREIGN KEY (tenant_id, job_id) REFERENCES jobs (tenant_id, job_id) ON DELETE CASCADE
);
CREATE INDEX idx_rejected_rows_job ON rejected_rows (tenant_id, job_id, id);
"""

_CLAIM_FNS = f"""
CREATE FUNCTION iia_claim_job() RETURNS TABLE (job_id uuid, tenant_id varchar)
LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
    UPDATE public.jobs j
       SET status = 'running', stage = 'claimed', started_at = {_NOW},
           locked_at = {_NOW}, finished_at = NULL
     WHERE j.job_id = (
        SELECT q.job_id FROM public.jobs q
         WHERE q.status = 'queued' AND q.run_after <= {_NOW}
         ORDER BY q.run_after, q.created_at
         FOR UPDATE SKIP LOCKED LIMIT 1)
    RETURNING j.job_id, j.tenant_id
$fn$;

CREATE FUNCTION iia_reap_stale_jobs(p_stale_seconds integer) RETURNS integer
LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
    WITH r AS (
        UPDATE public.jobs j
           SET status = CASE WHEN j.retry_count >= j.max_retries THEN 'failed' ELSE 'queued' END,
               retry_count = CASE WHEN j.retry_count >= j.max_retries
                                  THEN j.retry_count ELSE j.retry_count + 1 END,
               error = 'worker lost (no heartbeat for ' || p_stale_seconds || 's)',
               locked_at = NULL, run_after = {_NOW},
               finished_at = CASE WHEN j.retry_count >= j.max_retries THEN {_NOW} END
         WHERE j.status = 'running'
           AND j.locked_at < {_NOW} - make_interval(secs => p_stale_seconds)
        RETURNING 1)
    SELECT COUNT(*)::integer FROM r
$fn$;
"""

_GRANT_FN = """
CREATE OR REPLACE FUNCTION iia_grant_app_privileges() RETURNS void
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iia_app') THEN
        CREATE ROLE iia_app NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iia_worker') THEN
        CREATE ROLE iia_worker NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    END IF;
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM iia_app, iia_worker;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM iia_app, iia_worker;
    GRANT USAGE ON SCHEMA public TO iia_app, iia_worker;
    -- API role: reads, the audit log, and the upload/job records it creates.
    GRANT SELECT ON machines, sensor_summary, machine_anomalies, maintenance_records,
        sensor_registry, sensor_readings, tenant_settings, ai4i_reference,
        rejected_rows TO iia_app;
    GRANT SELECT, INSERT, UPDATE ON uploads, jobs TO iia_app;
    GRANT INSERT ON investigation_audit_log TO iia_app;
    GRANT USAGE ON SEQUENCE investigation_audit_log_id_seq TO iia_app;
    REVOKE ALL ON FUNCTION auth_lookup_tenant(text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION auth_lookup_tenant(text) TO iia_app;
    -- Worker role: writes the ingest pipeline's outputs, nothing else.
    GRANT SELECT ON ai4i_reference TO iia_worker;
    GRANT SELECT, UPDATE ON uploads, jobs TO iia_worker;
    GRANT SELECT, INSERT, DELETE ON rejected_rows TO iia_worker;
    GRANT SELECT, INSERT, UPDATE ON machines, sensor_registry, tenant_settings,
        sensor_summary, machine_anomalies, ingestion_checkpoints TO iia_worker;
    GRANT SELECT, INSERT ON sensor_readings TO iia_worker;
    GRANT USAGE ON SEQUENCE sensor_summary_id_seq, machine_anomalies_id_seq,
        rejected_rows_id_seq TO iia_worker;
    REVOKE ALL ON FUNCTION iia_claim_job() FROM PUBLIC;
    REVOKE ALL ON FUNCTION iia_reap_stale_jobs(integer) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION iia_claim_job() TO iia_worker;
    GRANT EXECUTE ON FUNCTION iia_reap_stale_jobs(integer) TO iia_worker;
    REVOKE ALL ON FUNCTION iia_enable_tenant_rls(regclass) FROM PUBLIC;
    REVOKE ALL ON FUNCTION iia_grant_app_privileges() FROM PUBLIC;
END
$fn$;
"""

# The 0006 definition, restored on downgrade.
_GRANT_FN_0006 = """
CREATE OR REPLACE FUNCTION iia_grant_app_privileges() RETURNS void
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iia_app') THEN
        CREATE ROLE iia_app NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    END IF;
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM iia_app;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM iia_app;
    GRANT USAGE ON SCHEMA public TO iia_app;
    GRANT SELECT ON machines, sensor_summary, machine_anomalies, maintenance_records,
        sensor_registry, sensor_readings, tenant_settings, ai4i_reference TO iia_app;
    GRANT INSERT ON investigation_audit_log TO iia_app;
    GRANT USAGE ON SEQUENCE investigation_audit_log_id_seq TO iia_app;
    REVOKE ALL ON FUNCTION auth_lookup_tenant(text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION auth_lookup_tenant(text) TO iia_app;
    REVOKE ALL ON FUNCTION iia_enable_tenant_rls(regclass) FROM PUBLIC;
    REVOKE ALL ON FUNCTION iia_grant_app_privileges() FROM PUBLIC;
END
$fn$;
"""


def _run(sql: str) -> None:
    # Raw driver SQL (no text() bind parsing); psycopg2 needs literal % doubled.
    op.get_bind().exec_driver_sql(sql.replace("%", "%%"))


def upgrade() -> None:
    conn = op.get_bind()
    dupes = conn.exec_driver_sql(
        "SELECT COUNT(*) FROM (SELECT 1 FROM machine_anomalies "
        "GROUP BY tenant_id, machine_id, detected_at HAVING COUNT(*) > 1) d").scalar()
    if dupes:
        raise RuntimeError(
            f"Refusing to upgrade: {dupes} (tenant, machine, detected_at) group(s) in "
            "machine_anomalies hold more than one row, so UNIQUE (tenant_id, machine_id, "
            "detected_at) cannot be added. De-duplicate them first.")

    _run("ALTER TABLE machines ALTER COLUMN production_line TYPE VARCHAR(100)")
    _run("ALTER TABLE machine_anomalies ADD CONSTRAINT uq_machine_anomalies_tenant_machine_detected "
         "UNIQUE (tenant_id, machine_id, detected_at)")
    _run(_TABLES)
    _run(_CLAIM_FNS)
    _run("SELECT iia_enable_tenant_rls('uploads')")
    _run("SELECT iia_enable_tenant_rls('rejected_rows')")
    # jobs: ENABLE only (see module docstring); same policy text as iia_enable_tenant_rls.
    _run("ALTER TABLE jobs ENABLE ROW LEVEL SECURITY")
    _run("CREATE POLICY tenant_isolation ON jobs "
         "USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')) "
         "WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))")
    _run(_GRANT_FN)
    _run("SELECT iia_grant_app_privileges()")


def downgrade() -> None:
    conn = op.get_bind()
    stored = conn.exec_driver_sql(
        "SELECT (SELECT COUNT(*) FROM uploads) + (SELECT COUNT(*) FROM jobs)").scalar()
    if stored:
        raise RuntimeError(
            f"Refusing to downgrade: {stored} upload/job row(s) would be dropped with the "
            "uploads, jobs and rejected_rows tables. Export or delete them first.")
    too_long = conn.exec_driver_sql(
        "SELECT COUNT(*) FROM machines WHERE length(production_line) > 20").scalar()
    if too_long:
        raise RuntimeError(
            f"Refusing to downgrade: {too_long} machine(s) have a production_line longer than "
            "20 characters, which the previous schema cannot hold.")

    _run("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iia_worker') THEN
                REVOKE ALL ON ALL TABLES IN SCHEMA public FROM iia_worker;
                REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM iia_worker;
                REVOKE ALL ON FUNCTION iia_claim_job() FROM iia_worker;
                REVOKE ALL ON FUNCTION iia_reap_stale_jobs(integer) FROM iia_worker;
                REVOKE ALL ON SCHEMA public FROM iia_worker;
            END IF;
        END $$
    """)
    _run("DROP TABLE rejected_rows")
    _run("DROP TABLE jobs")
    _run("DROP TABLE uploads")
    _run("DROP FUNCTION iia_reap_stale_jobs(integer)")
    _run("DROP FUNCTION iia_claim_job()")
    _run("ALTER TABLE machine_anomalies DROP CONSTRAINT uq_machine_anomalies_tenant_machine_detected")
    _run("ALTER TABLE machines ALTER COLUMN production_line TYPE VARCHAR(20)")
    _run(_GRANT_FN_0006)
    _run("SELECT iia_grant_app_privileges()")
