"""
Recommendation synthesis.

Two report builders live here, both returning the same
(recommendation, narrative, citations) shape and the same RESPONSE
FORMAT (## Machine / ## Risk / ## What changed? / ## Investigation /
## Possible causes / ## Supporting evidence / ## Recommended action /
## Confidence & limitations):

  - build_report(state) — Phase 5's deterministic template. String
    formatting only, no model call, no invented facts. Still the
    fallback used whenever Gemini synthesis is unavailable or disabled
    (see app/agents/nodes.py:build_recommendation).
  - build_report_with_llm(state, sections) — Phase 6. Takes prose
    sections already generated by Gemini (app/agents/llm.py) and
    assembles them into the same RESPONSE FORMAT, using the same
    deterministic citations/supporting-evidence logic as build_report
    (see _citations_and_supporting_evidence). Gemini writes prose; it
    never decides risk_level, root causes, or citations — those stay
    exactly as Phase 5 computed them (per EVIDENCE BEFORE EXPLANATION).

fleet_scan intent always uses _build_fleet_report regardless of which
of the two builders above is in play — see nodes.py for why Gemini
synthesis was kept out of that branch's scope.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any

from app.agents.state import AgentState

if TYPE_CHECKING:
    from app.agents.llm import GeminiReportSections


def _format_sensor_snapshot(sensor_evidence: dict[str, Any] | None) -> list[str]:
    if not sensor_evidence:
        return ["No recent sensor snapshot is available for this machine."]
    return [
        f"Latest window ({sensor_evidence['window_start']} to {sensor_evidence['window_end']}): "
        f"health_status={sensor_evidence['health_status']}, "
        f"anomalous readings={sensor_evidence['anomalous_reading_count']}/{sensor_evidence['reading_count']}, "
        f"max anomaly score={sensor_evidence['max_anomaly_score']}."
    ]


def _format_trend_delta(sensor_trend: list[dict[str, Any]]) -> list[str]:
    """Deterministic oldest-vs-newest comparison over the queried hourly
    windows. Query returns most-recent-first, so newest=index 0,
    oldest=index -1. Needs at least two windows to say anything about
    change; with fewer, there is nothing to compare.

    Audit F8 fallback only: this single-window-pair comparison is exactly
    what produced the "defect rate is down 0.172 -> 0.170" noise the audit
    flagged — a raw two-point delta with no sense of scale. It is kept
    only as a degraded-mode fallback for when compute_recent_vs_baseline
    doesn't have enough trend history to compare against (see
    build_report / build_report_with_llm below, and
    app.agents.nodes.gather_sensor_evidence for why sensor_trend itself
    stays short — this function still reads that short trend, not the
    longer sensor_trend_baseline).
    """
    if len(sensor_trend) < 2:
        return []
    newest, oldest = sensor_trend[0], sensor_trend[-1]
    lines = []
    for field, label in (
        ("avg_defect_rate", "defect rate"),
        ("avg_production_rate", "production rate"),
    ):
        old_val, new_val = oldest.get(field), newest.get(field)
        if old_val is None or new_val is None:
            continue
        delta = new_val - old_val
        if abs(delta) < 1e-9:
            continue
        direction = "up" if delta > 0 else "down"
        lines.append(
            f"{label} is {direction} from {old_val:.3f} to {new_val:.3f} "
            f"across the last {len(sensor_trend)} hourly windows."
        )
    return lines


# --- Audit F8 (finding 1): deterministic last-24h-vs-prior-baseline ---
#
# RECENT_WINDOW_COUNT mirrors risk.py's own "last day" framing (24 hourly
# windows). BASELINE_WINDOW_COUNT is the rest of a 7-day lookback. Both are
# windows *of the machine's own history*, not a cross-machine fleet
# average — the audit's fix bullet asked specifically for "last 24h vs
# prior 7d, with % change"; comparing against the rest of the fleet too
# would need a separate fleet-wide query on every single-machine
# investigation and was not what the fix called for.
RECENT_WINDOW_COUNT = 24
BASELINE_WINDOW_COUNT = 168
TREND_WINDOWS_FOR_BASELINE = RECENT_WINDOW_COUNT + BASELINE_WINDOW_COUNT
# Below this many prior-baseline windows there isn't enough history to
# call it a baseline (a handful of hours is exactly the transient-noise
# case risk.py's MIN_TREND_WINDOWS already guards against for risk_level;
# the same discipline applies here for the narrative).
_MIN_BASELINE_WINDOWS = 24


def _fmt_pct(rate: float | None) -> str | None:
    """0.172 -> '17.2%'. None passes through — 'no data', not 'zero'."""
    return None if rate is None else f"{rate * 100:.1f}%"


def _aggregate_trend_segment(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Reading-count-weighted aggregate over a slice of hourly windows —
    weighted, not a plain mean of per-window averages, since windows don't
    all have the same reading_count and an unweighted mean would let a
    sparse window count as much as a full one.
    """
    total_readings = sum(r.get("reading_count") or 0 for r in rows)
    total_anomalous = sum(r.get("anomalous_reading_count") or 0 for r in rows)
    weighted_defect = sum(
        (r.get("avg_defect_rate") or 0) * (r.get("reading_count") or 0) for r in rows
    )
    anomalous_rate = (total_anomalous / total_readings) if total_readings else None
    avg_defect_rate = (weighted_defect / total_readings) if total_readings else None
    return {
        "window_count": len(rows),
        "reading_count": total_readings,
        "anomalous_reading_count": total_anomalous,
        "anomalous_rate": anomalous_rate,
        "anomalous_rate_pct": _fmt_pct(anomalous_rate),
        "avg_defect_rate": avg_defect_rate,
        "avg_defect_rate_pct": _fmt_pct(avg_defect_rate),
    }


def _multiplier(new: float | None, old: float | None) -> float | None:
    """How many times the recent rate is the baseline rate — the "8x the
    fleet baseline" framing from the audit, applied to this machine's own
    prior period instead (see module comment above). None when either
    side is unusable (no data, or a zero baseline makes "times" undefined
    rather than infinite).
    """
    if new is None or old is None or old <= 0:
        return None
    return round(new / old, 1)


def compute_recent_vs_baseline(sensor_trend_baseline: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Deterministic last-24h vs prior-baseline comparison for the "What
    changed?" section (audit F8, finding 1) — replaces a raw newest-vs-
    oldest defect-rate delta (noise) with a reading-count-weighted
    anomalous-rate AND defect-rate comparison against this machine's own
    recent history, plus an explicit multiplier so the *scale* of a change
    is stated, not just its sign.

    Returns None when there isn't enough prior-baseline history yet
    (_MIN_BASELINE_WINDOWS) — callers fall back to _format_trend_delta.
    Input is most-recent-first, matching sensor_trend's convention.
    """
    if len(sensor_trend_baseline) < RECENT_WINDOW_COUNT + _MIN_BASELINE_WINDOWS:
        return None

    recent = sensor_trend_baseline[:RECENT_WINDOW_COUNT]
    baseline = sensor_trend_baseline[RECENT_WINDOW_COUNT:BASELINE_WINDOW_COUNT + RECENT_WINDOW_COUNT]

    recent_agg = _aggregate_trend_segment(recent)
    baseline_agg = _aggregate_trend_segment(baseline)

    return {
        "recent_24h": recent_agg,
        "prior_baseline": baseline_agg,
        "prior_baseline_days": round(len(baseline) / 24, 1),
        "anomalous_rate_multiplier": _multiplier(
            recent_agg["anomalous_rate"], baseline_agg["anomalous_rate"]),
        "defect_rate_multiplier": _multiplier(
            recent_agg["avg_defect_rate"], baseline_agg["avg_defect_rate"]),
    }


def _format_baseline_comparison(comparison: dict[str, Any]) -> list[str]:
    """Render compute_recent_vs_baseline's output as the "What changed?"
    bullet lines — the same numbers/percentages this function emits are
    also what app.agents.llm._build_prompt puts in the Gemini evidence
    payload (see that module), so a hallucination-guardrail check that a
    percentage in Gemini's prose exists somewhere in the evidence JSON
    (llm._validate_report_against_evidence) has a literal string to find,
    not just a raw float it would have to reformat to match.
    """
    recent, baseline = comparison["recent_24h"], comparison["prior_baseline"]
    lines = []

    if recent["anomalous_rate_pct"] is not None:
        line = (
            f"Anomalous-reading rate, last 24h: {recent['anomalous_rate_pct']} "
            f"({recent['anomalous_reading_count']}/{recent['reading_count']} readings)"
        )
        if baseline["anomalous_rate_pct"] is not None:
            line += f", vs {baseline['anomalous_rate_pct']} over the prior {comparison['prior_baseline_days']:g} days"
            mult = comparison["anomalous_rate_multiplier"]
            if mult is not None and mult >= 1.5:
                line += f" — about {mult:g}x the machine's own recent baseline"
            elif mult is not None and mult <= 0.67:
                line += f" — about {mult:g}x (a drop from) the machine's own recent baseline"
        lines.append(line + ".")

    if recent["avg_defect_rate_pct"] is not None and baseline["avg_defect_rate_pct"] is not None:
        mult = comparison["defect_rate_multiplier"]
        note = ""
        if mult is not None and (mult >= 1.5 or mult <= 0.67):
            note = f" — about {mult:g}x the prior baseline"
        else:
            note = " — within normal noise of the prior baseline"
        lines.append(
            f"Average defect rate, last 24h: {recent['avg_defect_rate_pct']}, "
            f"vs {baseline['avg_defect_rate_pct']} over the prior "
            f"{comparison['prior_baseline_days']:g} days{note}."
        )

    return lines


def _what_changed_lines(state: AgentState) -> list[str]:
    """Shared by build_report and _build_prompt (via state, not this
    function directly — llm.py calls compute_recent_vs_baseline itself so
    it can also embed the structured numbers, not just this prose).
    Prefers the baseline comparison; falls back to the old newest-vs-
    oldest delta when there isn't enough trend history for one yet
    (a new machine, or a machine still building up sensor_summary rows).
    """
    baseline_trend = state.get("sensor_trend_baseline") or []
    comparison = compute_recent_vs_baseline(baseline_trend)
    if comparison is not None:
        lines = _format_baseline_comparison(comparison)
        if lines:
            return lines
    return _format_trend_delta(state.get("sensor_trend") or [])


def _format_what_changed(anomaly_metrics: list[dict[str, Any]]) -> list[str]:
    if not anomaly_metrics:
        return ["No anomaly events were flagged in the queried window."]
    lines = []
    for a in anomaly_metrics[:5]:  # most recent first, already ordered by the query
        reasons = a.get("triggered_reasons") or "unspecified trigger"
        lines.append(
            f"{a['detected_at']} — {a['severity']} severity (score {a['anomaly_score']}): {reasons}")
    if len(anomaly_metrics) > 5:
        lines.append(
            f"...and {len(anomaly_metrics) - 5} more anomaly event(s) in the queried window.")
    return lines


# Mirrors spark_jobs/anomaly_detection.py's flag_descriptions dict, which is
# the single source of truth for how a triggered_reasons string is worded.
# triggered_reasons arrives here as one array_join'd string per anomaly row
# (e.g. "Tool wear in AI4I TWF failure window (200-240 min); Torque
# statistically unlike this machine's recent history"), with the per-flag
# boolean columns already collapsed away — so the failure mode has to be
# recovered from the wording rather than read off a structured field. If
# the wording in the Spark job changes, this mapping goes stale silently;
# a test asserts the two stay in sync (see tests/test_llm_synthesis.py or
# tests/test_agent.py's root-cause coverage).
#
# The four AI4I threshold flags name a specific, published failure mode,
# so they map directly. The five statistical (z-score) flags don't — a
# reading being unlike a machine's own recent history says nothing about
# *why*, and asserting OSF/PWF/etc. from a torque or power blip alone
# would be a stronger causal claim than the evidence supports (AI SAFETY /
# DECISION SUPPORT). RNF ("random failure") is the AI4I label for exactly
# this situation — an anomaly with no discernible physical precursor — so
# statistical flags map there instead of to a specific mechanical mode.
_FAILURE_MODE_REASON_PHRASES: list[tuple[str, str]] = [
    ("ai4i twf failure window", "TWF"),
    ("heat dissipation failure pattern", "HDF"),
    ("power outside safe operating band", "PWF"),
    ("overstrain", "OSF"),
    ("statistically unlike this machine's recent history", "RNF"),
]

# The Spark-produced wording for the TWF flag happens to contain the
# literal code ("...AI4I TWF failure window..."), but HDF/PWF/OSF don't —
# so phrase matching alone is required for those. This second pattern
# additionally recognizes a bare code (as callers/tests may pass, e.g.
# triggered_reasons="OSF" in fixtures, or a future terser wording),
# matched as a whole word so it can't fire on an unrelated substring.
_FAILURE_MODE_CODE_PATTERN = re.compile(
    r"\b(TWF|HDF|PWF|OSF|RNF)\b", re.IGNORECASE)


def infer_failure_modes(reason: str) -> set[str]:
    """Every failure mode implicated by one triggered_reasons string.

    A single anomaly row can trip more than one flag (semicolon-joined),
    so this returns a set, not a single mode. Empty when the wording
    doesn't match anything known — see the module-sync note above.

    Public (audit F6): also used by app.agents.nodes' rule-based
    maintenance-doc query reformulation, not just root-cause matching
    here — a failure mode implicated by the anomaly log is exactly the
    filter a retry-with-a-narrower-query step should use.
    """
    modes = {code.upper()
             for code in _FAILURE_MODE_CODE_PATTERN.findall(reason)}
    lowered = reason.lower()
    modes.update(code for phrase,
                 code in _FAILURE_MODE_REASON_PHRASES if phrase in lowered)
    return modes


def build_root_cause_candidates(
    anomaly_metrics: list[dict[str, Any]],
    maintenance_evidence: list[dict[str, Any]],
    ai4i_reference_rates: dict[str, dict[str, Any]] | None = None,
) -> list[str]:
    """Deterministic candidate list: distinct triggered_reasons from the
    anomaly log, each explicitly labeled a possible cause (never a proven
    one — see AI SAFETY / DECISION SUPPORT), cross-referenced against
    whether documentation for *that specific failure mode* exists. No
    causal claim is stronger than "coincided with" / "documentation
    identifies" per the master prompt's own bad/better example.

    A retrieved chunk only counts as supporting a cause when the two
    share a failure mode (SOP-101 covers TWF/OSF; citing it for a HDF
    reading is not "related documentation", it's a retrieval hit that
    happened to also come back for this machine). Previously every cause
    was credited with whatever maintenance_evidence the retrieval step
    returned, regardless of topic — see audit F3.

    ai4i_reference_rates (P2 cleanup): optional, from
    queries.get_ai4i_failure_mode_rates — real-world incidence, among the
    published UCI AI4I 2020 dataset's actual failures, of whichever mode(s)
    a candidate implicates. Appended as a plainly-labeled real-dataset
    statistic, never as support for *this machine's* cause — a mode being
    common in the real dataset says nothing about whether it explains
    this reading, it just gives a human reader external context the
    synthetic fleet alone can't. Silently omitted when not provided or
    when a candidate implicates no known mode, so every existing call site
    (and this function's own tests) keeps working unchanged.
    """
    reasons = []
    seen = set()
    for a in anomaly_metrics:
        reason = (a.get("triggered_reasons") or "").strip()
        if reason and reason not in seen:
            seen.add(reason)
            reasons.append(reason)

    if not reasons:
        return ["No recurring anomaly trigger was observed — insufficient evidence to propose a cause."]

    candidates = []
    for reason in reasons:
        inferred_modes = infer_failure_modes(reason)
        matching_doc_ids = sorted({
            d["doc_id"] for d in maintenance_evidence
            if inferred_modes & set(d.get("failure_modes") or [])
        }) if inferred_modes else []

        if matching_doc_ids:
            # Audit F8 (finding 2): this used to say "warrants inspection"
            # unconditionally, which directly contradicted a LOW-risk
            # report's own "no inspection priority indicated" recommendation
            # line (build_report / build_report_with_llm, below) whenever a
            # low-risk machine still had one documented candidate. Whether
            # anything "warrants inspection" is an action call the top-level
            # ## Recommended action line already makes from risk_level — a
            # per-candidate line's only job is to describe evidentiary
            # support, neutrally, not to recommend an action a LOW risk
            # report is simultaneously saying not to take.
            candidate = (
                f"Possible cause: {reason}. This coincided with the observed anomaly readings, and "
                f"maintenance documentation ({', '.join(matching_doc_ids)}) describes related "
                f"failure patterns for this failure mode — the evidence is consistent with this "
                f"cause, not confirmation of it."
            )
        else:
            candidate = (
                f"Possible cause: {reason}. This coincided with the observed anomaly readings; no matching "
                f"maintenance documentation was found, so this remains an unconfirmed observation."
            )

        candidate += _ai4i_context_suffix(inferred_modes, ai4i_reference_rates)
        candidates.append(candidate)
    return candidates


def _ai4i_context_suffix(
    inferred_modes: set[str], ai4i_reference_rates: dict[str, dict[str, Any]] | None
) -> str:
    """The real-dataset context sentence appended to a root-cause
    candidate, or "" when there's nothing to add (no rates supplied, or
    this candidate implicates no known AI4I mode). Kept out of
    build_root_cause_candidates' main loop so the "is this real-dataset
    context, or an evidentiary claim about this machine" line stays
    visually obvious in the source, not just in the docstring."""
    if not ai4i_reference_rates or not inferred_modes:
        return ""
    parts = []
    for mode in sorted(inferred_modes):
        stats = ai4i_reference_rates.get(mode)
        if not stats or not stats.get("total_real_failures"):
            continue
        pct = stats["share_of_real_failures"] * 100
        parts.append(
            f"{mode} was implicated in {pct:.0f}% of failures in the real "
            f"UCI AI4I 2020 dataset ({stats['failure_count']}/{stats['total_real_failures']} "
            f"real failures)"
        )
    if not parts:
        return ""
    return " For reference, in the published real-world dataset (not this synthetic fleet): " + \
        "; ".join(parts) + "."


def _build_fleet_report(state: AgentState) -> tuple[str, str, list[str]]:
    """Fleet-wide branch: "which machines currently show abnormal
    behavior?" has no single machine, no anomaly log, no maintenance
    docs to cite — a per-machine RESPONSE FORMAT report doesn't apply.
    Ranks get_fleet_status's rows deterministically (AT_RISK first,
    then WATCH, then by max_anomaly_score) rather than asking anything
    to guess an order.
    """
    fleet_ranking = state.get("fleet_ranking") or []
    errors = state.get("errors") or []

    # Phase 9 fix: rank/flag on risk_level (nodes.py's fleet_scan attaches
    # it via the same risk.assess_risk rule a single-machine investigation
    # uses), not health_status — health_status is just the single latest
    # hourly window and is too noisy to flag on by itself (see risk.py's
    # module docstring on lone WATCH snapshots).
    # UNKNOWN ranks ahead of MEDIUM/LOW, behind HIGH: a machine we
    # couldn't assess deserves a re-check sooner than one we know is
    # only medium-risk, but a confirmed HIGH is still more urgent.
    risk_rank = {"HIGH": 0, "UNKNOWN": 1, "MEDIUM": 2, "LOW": 3}
    # Ties on risk_level are common (a MEDIUM machine with 12/12 anomalous
    # readings and one with 1/12 both round to the same bucket), so break
    # them by anomalous-reading count in the latest window, then
    # machine_id for a stable order.
    ranked = sorted(
        fleet_ranking,
        key=lambda m: (
            risk_rank.get(m.get("risk_level"), 3),
            -(m.get("max_anomaly_score") or 0),
            -(m.get("anomalous_reading_count") or 0),
            m.get("machine_id") or "",
        ),
    )
    flagged = [m for m in ranked if m.get("risk_level", "UNKNOWN") != "LOW"]

    if flagged:
        recommendation = "Machines flagged for inspection, most urgent first: " + ", ".join(
            f"{m['machine_id']} ({m.get('risk_level', 'UNKNOWN')})" for m in flagged
        )
    else:
        recommendation = "No machines currently show abnormal behavior across the fleet."

    lines = [f"- {m['machine_id']} ({m.get('production_line', 'unknown line')}): "
             f"risk={m.get('risk_level', 'UNKNOWN')}, latest hourly status {m['health_status']}, "
             f"max anomaly score {m.get('max_anomaly_score')}, "
             f"{m.get('anomalous_reading_count')} anomalous readings in latest window"
             for m in ranked]

    limitations = (
        "Fleet-wide scan computes each machine's risk_level the same way a single-machine "
        "investigation does, but does not investigate root cause for any individual machine. "
        "Run a machine-specific investigation (provide machine_id) for that."
    )
    if errors:
        limitations += " Note: " + "; ".join(errors)

    narrative = "\n\n".join([
        "## Fleet status",
        "\n".join(lines) if lines else "- No fleet status data available.",
        f"## Recommended action\n{recommendation}",
        f"## Confidence & limitations\n{limitations}",
    ])
    return recommendation, narrative, []


def _citations_and_supporting_evidence(state: AgentState) -> tuple[list[str], list[str]]:
    """Shared between build_report and build_report_with_llm — citations
    and the raw evidence list are always code-derived from
    maintenance_evidence/historical_evidence, never from LLM output (see
    llm.py's module docstring: an LLM is not a trustworthy source for
    which doc_ids were actually retrieved).
    """
    maintenance_evidence = state.get("maintenance_evidence") or []
    historical_evidence = state.get("historical_evidence") or []
    sensor_evidence = state.get("sensor_evidence")

    # Several retrieved chunks can come from the same doc section; cite each
    # section once (dict.fromkeys de-duplicates while keeping rank order).
    citations = list(dict.fromkeys(d["citation"]
                     for d in maintenance_evidence))
    supporting_evidence = list(citations)
    if sensor_evidence:
        supporting_evidence.append(
            f"sensor_summary window {sensor_evidence['window_start']}\u2013{sensor_evidence['window_end']}"
        )
    for record in historical_evidence[:3]:
        supporting_evidence.append(
            f"maintenance_records: {record['event_date']} {record['event_type']} "
            f"(resolved={record['resolved']})"
        )
    return citations, supporting_evidence


def build_report(state: AgentState) -> tuple[str, str, list[str]]:
    """Build (recommendation, narrative, citations) from the state's
    evidence. `recommendation` is the short actionable line; `narrative`
    is the full RESPONSE FORMAT markdown.
    """
    if state.get("intent") == "fleet_scan":
        return _build_fleet_report(state)

    machine_id = state.get("machine_id") or "unspecified"
    risk_level = state.get("risk_level") or "UNKNOWN"
    sensor_evidence = state.get("sensor_evidence")
    anomaly_metrics = state.get("anomaly_metrics") or []
    root_cause_candidates = state.get("root_cause_candidates") or []
    errors = state.get("errors") or []

    citations, supporting_evidence = _citations_and_supporting_evidence(state)

    if risk_level == "HIGH":
        recommendation = (
            f"Recommend prioritizing {machine_id} for immediate physical inspection — "
            "current evidence shows sustained anomalous readings, elevated anomaly severity "
            "and/or an AT_RISK health status."
        )
    elif risk_level == "MEDIUM":
        recommendation = (
            f"Recommend scheduling {machine_id} for inspection during the next maintenance window — "
            "evidence shows a WATCH-level health status and/or medium-severity anomalies, not yet critical."
        )
    elif risk_level == "UNKNOWN":
        recommendation = (
            f"Risk for {machine_id} could not be assessed — no sensor snapshot, trend or anomaly "
            "data was available for this investigation. Re-run once evidence-gathering succeeds "
            "before treating this as a healthy machine."
        )
    else:
        recommendation = f"No inspection priority indicated for {machine_id} based on current evidence."

    limitations = (
        "This report is evidence-backed but not a diagnosis: root causes are hypotheses, not confirmed "
        "failures. It reflects only the sensor window, anomaly log, and maintenance documentation queried "
        "above, generated deterministically from that evidence via a fixed template (Gemini-based synthesis "
        "was unavailable or disabled for this request, so no LLM was involved in wording this report). "
        "Always confirm with a qualified technician before acting."
    )
    if errors:
        limitations += " Note: " + "; ".join(errors)

    narrative_lines = [
        f"## Machine\n{machine_id}",
        f"## Risk\n{risk_level}",
        "## What changed?\n"
        + "\n".join(f"- {line}" for line in (_what_changed_lines(state) +
                    _format_what_changed(anomaly_metrics))),
        "## Investigation\nChecked latest sensor health snapshot, recent anomaly events, maintenance "
        "history, and searched the maintenance knowledge base for related documentation.\n"
        + "\n".join(f"- {line}" for line in _format_sensor_snapshot(sensor_evidence)),
        "## Possible causes\n" +
        "\n".join(f"- {c}" for c in root_cause_candidates),
        "## Supporting evidence\n"
        + ("\n".join(f"- {e}" for e in supporting_evidence)
           if supporting_evidence else "- None available."),
        f"## Recommended action\n{recommendation}",
        f"## Confidence & limitations\n{limitations}",
    ]
    narrative = "\n\n".join(narrative_lines)

    return recommendation, narrative, citations


def build_report_with_llm(state: AgentState, sections: "GeminiReportSections") -> tuple[str, str, list[str]]:
    """Assemble the same RESPONSE FORMAT report as build_report, but with
    the prose sections written by Gemini (app/agents/llm.py) instead of
    the string templates above. Only called for machine_investigation —
    fleet_scan always stays on _build_fleet_report (see nodes.py).

    `## Machine` / `## Risk` stay deterministic here too: they're a
    direct echo of already-known data, not something worth spending a
    model call to restate. Citations and supporting evidence are still
    built by _citations_and_supporting_evidence — never by Gemini (see
    llm.py's module docstring on why).
    """
    machine_id = state.get("machine_id") or "unspecified"
    risk_level = state.get("risk_level") or "UNKNOWN"
    errors = state.get("errors") or []
    citations, supporting_evidence = _citations_and_supporting_evidence(state)

    limitations = sections.confidence_limitations
    if errors:
        limitations += " Note: " + "; ".join(errors)

    narrative_lines = [
        f"## Machine\n{machine_id}",
        f"## Risk\n{risk_level}",
        "## What changed?\n" +
        "\n".join(f"- {line}" for line in sections.what_changed),
        f"## Investigation\n{sections.investigation_summary}",
        "## Possible causes\n" +
        "\n".join(f"- {c}" for c in sections.possible_causes_prose),
        "## Supporting evidence\n"
        + ("\n".join(f"- {e}" for e in supporting_evidence)
           if supporting_evidence else "- None available."),
        f"## Recommended action\n{sections.recommended_action}",
        f"## Confidence & limitations\n{limitations}",
    ]
    narrative = "\n\n".join(narrative_lines)

    return sections.recommended_action, narrative, citations
