-- Industrial Intelligence Agent — Phase 2 schema
--
-- Reflects what the Phase 1 PySpark pipeline actually produces (verified
-- against data/processed/*.parquet), not the original Phase 0 sketch.
-- Deviations from Phase 0 are called out inline.

-- ---------------------------------------------------------------------
-- machines — dimension table, one row per fleet machine (18 rows)
-- ---------------------------------------------------------------------
-- name/install_date/location were never generated by Phase 1 (the
-- generator only produces machine_id, production_line and the AI4I-style
-- quality variant "type"). Kept here as nullable so the schema doesn't
-- need to change if real/plausible metadata is added later, but nothing
-- populates them yet — they will be NULL, not fabricated.
CREATE TABLE machines (
    machine_id       VARCHAR(10)  PRIMARY KEY,
    production_line  VARCHAR(20)  NOT NULL,
    type             CHAR(1)      NOT NULL CHECK (type IN ('L', 'M', 'H')),
    name             VARCHAR(100),
    install_date     DATE,
    location         VARCHAR(100)
);

CREATE INDEX idx_machines_production_line ON machines (production_line);


-- ---------------------------------------------------------------------
-- sensor_summary — hourly rollup, one row per (machine, hour)
-- ---------------------------------------------------------------------
-- production_line/type are dropped here vs. the raw parquet (which
-- denormalizes them into every row for Spark's convenience) — they're
-- reachable via a join to machines instead, so there's one place a
-- machine's line/type can ever be wrong.
CREATE TABLE sensor_summary (
    id                          BIGSERIAL PRIMARY KEY,
    machine_id                  VARCHAR(10) NOT NULL REFERENCES machines(machine_id),
    window_start                TIMESTAMP   NOT NULL,
    window_end                  TIMESTAMP   NOT NULL,
    avg_air_temp_k               DOUBLE PRECISION,
    avg_process_temp_k           DOUBLE PRECISION,
    avg_rotational_speed_rpm     DOUBLE PRECISION,
    avg_torque_nm                DOUBLE PRECISION,
    tool_wear_min                DOUBLE PRECISION,
    avg_production_rate          DOUBLE PRECISION,
    avg_energy_consumption_kwh   DOUBLE PRECISION,
    avg_defect_rate               DOUBLE PRECISION,
    reading_count                INTEGER NOT NULL,
    anomalous_reading_count      INTEGER NOT NULL DEFAULT 0,
    max_anomaly_score            INTEGER NOT NULL DEFAULT 0,
    health_status                VARCHAR(10) NOT NULL CHECK (health_status IN ('HEALTHY', 'WATCH', 'AT_RISK')),
    UNIQUE (machine_id, window_start)
);

-- Every query the agent's tools will run is "this machine's recent
-- history" (get_sensor_summary, get_machine_health) — composite index
-- with machine_id first serves those directly, and Postgres can still
-- use the leading column alone for machine-only lookups.
CREATE INDEX idx_sensor_summary_machine_window ON sensor_summary (machine_id, window_start);

-- Fleet-wide "which machines currently look abnormal" needs the latest
-- window across ALL machines, not one machine's history — a plain index
-- on window_start supports that scan pattern.
CREATE INDEX idx_sensor_summary_window_start ON sensor_summary (window_start);


-- ---------------------------------------------------------------------
-- machine_anomalies — event table, only rows that crossed a threshold
-- ---------------------------------------------------------------------
-- Deviation from Phase 0: no metric_name column. The pipeline computes
-- one combined score per flagged timestamp and lists every rule that
-- fired in triggered_reasons (free text), so the schema follows what the
-- pipeline actually emits rather than a per-metric row shape it doesn't
-- populate. No LOW severity rows exist by construction (this table only
-- holds flagged readings), so severity is constrained to what's real.
CREATE TABLE machine_anomalies (
    id                  BIGSERIAL PRIMARY KEY,
    machine_id          VARCHAR(10) NOT NULL REFERENCES machines(machine_id),
    detected_at         TIMESTAMP   NOT NULL,
    anomaly_score       INTEGER     NOT NULL,
    severity            VARCHAR(10) NOT NULL CHECK (severity IN ('MEDIUM', 'HIGH')),
    triggered_reasons   TEXT
);

CREATE INDEX idx_machine_anomalies_machine_detected ON machine_anomalies (machine_id, detected_at);

-- "Which machines should the maintenance team inspect first" ranks
-- across the whole fleet by recency + severity, not per machine.
CREATE INDEX idx_machine_anomalies_severity_detected ON machine_anomalies (severity, detected_at);


-- ---------------------------------------------------------------------
-- maintenance_records — human-logged events, 7 rows in Phase 1 data
-- ---------------------------------------------------------------------
CREATE TABLE maintenance_records (
    id                  SERIAL PRIMARY KEY,
    machine_id          VARCHAR(10) NOT NULL REFERENCES machines(machine_id),
    event_date          DATE        NOT NULL,
    event_type          VARCHAR(50) NOT NULL,
    technician_notes    TEXT,
    resolved            BOOLEAN     NOT NULL
);

CREATE INDEX idx_maintenance_records_machine_date ON maintenance_records (machine_id, event_date);


-- ---------------------------------------------------------------------
-- ai4i_reference — the real UCI AI4I 2020 dataset, 10,000 rows
-- ---------------------------------------------------------------------
-- Deliberately NOT tied to the 18-machine fleet: udi/product_id are the
-- real dataset's own identifiers, unrelated to our machine_id scheme. No
-- FK to machines. This table exists so the agent (or a human) can point
-- at real published data behind the threshold formulas, e.g. "what does
-- the real dataset show for machines with PWF=1", rather than only ever
-- reasoning over the synthetic fleet.
CREATE TABLE ai4i_reference (
    udi                     INTEGER PRIMARY KEY,
    product_id              VARCHAR(20) NOT NULL,
    type                    CHAR(1)     NOT NULL CHECK (type IN ('L', 'M', 'H')),
    air_temperature_k       DOUBLE PRECISION,
    process_temperature_k   DOUBLE PRECISION,
    rotational_speed_rpm    DOUBLE PRECISION,
    torque_nm               DOUBLE PRECISION,
    tool_wear_min           DOUBLE PRECISION,
    machine_failure         SMALLINT NOT NULL,
    twf                     SMALLINT NOT NULL,
    hdf                     SMALLINT NOT NULL,
    pwf                     SMALLINT NOT NULL,
    osf                     SMALLINT NOT NULL,
    rnf                     SMALLINT NOT NULL
);

-- Only query pattern anticipated for this table is "show me real failure
-- examples of type X" — index the failure flag, not much else needed.
CREATE INDEX idx_ai4i_reference_machine_failure ON ai4i_reference (machine_failure);
