-- Industrial Intelligence Agent — schema (multi-tenant since 0002; generic sensors 0005; row-level security 0006)
--
-- Reflects what the Phase 1 PySpark pipeline actually produces (verified
-- against data/processed/*.parquet), not the original Phase 0 sketch.
-- Deviations from Phase 0 are called out inline.
--
-- This file is the FULL CURRENT SCHEMA, used by docker-compose's init
-- script and CI. It must stay identical to what `alembic upgrade head`
-- produces (tests/test_migrations.py checks this). To change the schema:
-- add an Alembic migration under migrations/versions/, then update this
-- file to match.
--
-- Multi-tenancy (production-readiness fix 1): every table that holds a
-- company's data carries `tenant_id`, and every query in
-- app/database/queries.py filters on it. Machine ids are unique per
-- tenant, not globally, so two companies can both own an "M-01".
-- `ai4i_reference` is deliberately NOT tenant-scoped: it is the public UCI
-- AI4I 2020 dataset, shared read-only reference data, not company data.
--
-- `tenant_id ... DEFAULT 'default'` exists only so the committed seed
-- (sql/seed.sql.gz, a COPY dump written before tenancy that names its
-- columns explicitly) still loads into the demo tenant. Application code
-- never relies on it: queries pass tenant_id explicitly, and loaders take
-- an explicit --tenant.

-- ---------------------------------------------------------------------
-- tenants — one row per company; holds the hashed API credential
-- ---------------------------------------------------------------------
-- api_key_hash is SHA-256 of a random 256-bit key (see
-- app/core/tenancy.hash_api_key); the key itself is never stored. NULL
-- means "no credential issued yet" — that tenant cannot authenticate.
CREATE TABLE tenants (
    tenant_id      VARCHAR(48)  PRIMARY KEY CHECK (tenant_id ~ '^[a-z0-9][a-z0-9_-]{0,47}$'),
    name           VARCHAR(200) NOT NULL,
    api_key_hash   CHAR(64)     UNIQUE,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

INSERT INTO tenants (tenant_id, name) VALUES ('default', 'Demo tenant (synthetic fleet)');


-- ---------------------------------------------------------------------
-- machines — dimension table, one row per fleet machine (18 rows in the demo tenant)
-- ---------------------------------------------------------------------
-- name/install_date/location were never generated by Phase 1 (the
-- generator only produces machine_id, production_line and the AI4I-style
-- quality variant "type"). Kept here as nullable so the schema doesn't
-- need to change if real/plausible metadata is added later, but nothing
-- populates them yet — they will be NULL, not fabricated.
CREATE TABLE machines (
    tenant_id        VARCHAR(48)  NOT NULL DEFAULT 'default' REFERENCES tenants(tenant_id),
    machine_id       VARCHAR(64)  NOT NULL,
    production_line  VARCHAR(20)  NOT NULL,
    -- NULL for fleets with no AI4I quality variant (0005); non-NULL must still be L/M/H.
    type             CHAR(1)      CHECK (type IN ('L', 'M', 'H')),
    name             VARCHAR(100),
    install_date     DATE,
    location         VARCHAR(100),
    PRIMARY KEY (tenant_id, machine_id)
);

CREATE INDEX idx_machines_production_line ON machines (tenant_id, production_line);


-- ---------------------------------------------------------------------
-- sensor_summary — hourly rollup, one row per (machine, hour)
-- ---------------------------------------------------------------------
-- production_line/type are dropped here vs. the raw parquet (which
-- denormalizes them into every row for Spark's convenience) — they're
-- reachable via a join to machines instead, so there's one place a
-- machine's line/type can ever be wrong.
--
-- Partitioned by RANGE(window_start) (production-readiness fix 13): see
-- migrations/versions/0004_partition_timeseries_tables.py for why this
-- starts as a single DEFAULT partition rather than fixed calendar
-- bounds, and scripts/manage_partitions.py for creating dedicated
-- partitions going forward. `id` moves out of being a lone PRIMARY KEY
-- and into PRIMARY KEY (window_start, id): Postgres requires every
-- unique constraint on a partitioned table to include the partition
-- key, and `id` is never referenced by application code (only ever an
-- opaque surrogate), so this changes nothing observable.
CREATE SEQUENCE sensor_summary_id_seq;

CREATE TABLE sensor_summary (
    id                          BIGINT      NOT NULL DEFAULT nextval('sensor_summary_id_seq'),
    tenant_id                   VARCHAR(48) NOT NULL DEFAULT 'default',
    machine_id                  VARCHAR(64) NOT NULL,
    window_start                TIMESTAMP   NOT NULL,
    window_end                  TIMESTAMP   NOT NULL,
    avg_air_temp_k               DOUBLE PRECISION,
    avg_process_temp_k           DOUBLE PRECISION,
    avg_rotational_speed_rpm     DOUBLE PRECISION,
    avg_torque_nm                DOUBLE PRECISION,
    tool_wear_min                DOUBLE PRECISION,
    avg_production_rate          DOUBLE PRECISION,
    avg_energy_consumption_kwh   DOUBLE PRECISION,
    avg_defect_rate               DOUBLE PRECISION,
    reading_count                INTEGER NOT NULL,
    anomalous_reading_count      INTEGER NOT NULL DEFAULT 0,
    max_anomaly_score            INTEGER NOT NULL DEFAULT 0,
    health_status                VARCHAR(10) NOT NULL CHECK (health_status IN ('HEALTHY', 'WATCH', 'AT_RISK')),
    PRIMARY KEY (window_start, id),
    UNIQUE (tenant_id, machine_id, window_start),
    -- Composite FK: a sensor row can only point at a machine of the SAME tenant.
    FOREIGN KEY (tenant_id, machine_id) REFERENCES machines (tenant_id, machine_id)
) PARTITION BY RANGE (window_start);

CREATE TABLE sensor_summary_default PARTITION OF sensor_summary DEFAULT;

ALTER SEQUENCE sensor_summary_id_seq OWNED BY sensor_summary.id;

-- Every query the agent's tools will run is "this tenant's machine's
-- recent history" (get_sensor_summary, get_machine_health) — composite
-- index with tenant_id, machine_id first serves those directly, and Postgres can still
-- use the leading column alone for machine-only lookups.
CREATE INDEX idx_sensor_summary_machine_window ON sensor_summary (tenant_id, machine_id, window_start);

-- Fleet-wide "which machines currently look abnormal" needs the latest
-- window across ALL machines, not one machine's history — a plain index
-- on window_start supports that scan pattern.
CREATE INDEX idx_sensor_summary_window_start ON sensor_summary (tenant_id, window_start);


-- ---------------------------------------------------------------------
-- machine_anomalies — event table, only rows that crossed a threshold
-- ---------------------------------------------------------------------
-- Deviation from Phase 0: no metric_name column. The pipeline computes
-- one combined score per flagged timestamp and lists every rule that
-- fired in triggered_reasons (free text), so the schema follows what the
-- pipeline actually emits rather than a per-metric row shape it doesn't
-- populate. No LOW severity rows exist by construction (this table only
-- holds flagged readings), so severity is constrained to what's real.
CREATE SEQUENCE machine_anomalies_id_seq;

CREATE TABLE machine_anomalies (
    id                  BIGINT      NOT NULL DEFAULT nextval('machine_anomalies_id_seq'),
    tenant_id           VARCHAR(48) NOT NULL DEFAULT 'default',
    machine_id          VARCHAR(64) NOT NULL,
    detected_at         TIMESTAMP   NOT NULL,
    anomaly_score       INTEGER     NOT NULL,
    severity            VARCHAR(10) NOT NULL CHECK (severity IN ('MEDIUM', 'HIGH')),
    triggered_reasons   TEXT,
    PRIMARY KEY (detected_at, id),
    FOREIGN KEY (tenant_id, machine_id) REFERENCES machines (tenant_id, machine_id)
) PARTITION BY RANGE (detected_at);
-- Partitioned like sensor_summary (fix 13); PK includes the partition key.

CREATE TABLE machine_anomalies_default PARTITION OF machine_anomalies DEFAULT;

ALTER SEQUENCE machine_anomalies_id_seq OWNED BY machine_anomalies.id;

CREATE INDEX idx_machine_anomalies_machine_detected ON machine_anomalies (tenant_id, machine_id, detected_at);

-- "Which machines should the maintenance team inspect first" ranks
-- across the whole fleet by recency + severity, not per machine.
CREATE INDEX idx_machine_anomalies_severity_detected ON machine_anomalies (tenant_id, severity, detected_at);


-- ---------------------------------------------------------------------
-- maintenance_records — human-logged events, 7 rows in the demo tenant
-- ---------------------------------------------------------------------
CREATE TABLE maintenance_records (
    id                  SERIAL PRIMARY KEY,
    tenant_id           VARCHAR(48) NOT NULL DEFAULT 'default',
    machine_id          VARCHAR(64) NOT NULL,
    event_date          DATE        NOT NULL,
    event_type          VARCHAR(50) NOT NULL,
    technician_notes    TEXT,
    resolved            BOOLEAN     NOT NULL,
    FOREIGN KEY (tenant_id, machine_id) REFERENCES machines (tenant_id, machine_id)
);

CREATE INDEX idx_maintenance_records_machine_date ON maintenance_records (tenant_id, machine_id, event_date);


-- ---------------------------------------------------------------------
-- ai4i_reference — the real UCI AI4I 2020 dataset, 10,000 rows
-- ---------------------------------------------------------------------
-- Deliberately NOT tied to the 18-machine fleet: udi/product_id are the
-- real dataset's own identifiers, unrelated to our machine_id scheme. No
-- FK to machines. This table exists so the agent (or a human) can point
-- at real published data behind the threshold formulas, e.g. "what does
-- the real dataset show for machines with PWF=1", rather than only ever
-- reasoning over the synthetic fleet.
CREATE TABLE ai4i_reference (
    udi                     INTEGER PRIMARY KEY,
    product_id              VARCHAR(20) NOT NULL,
    type                    CHAR(1)     NOT NULL CHECK (type IN ('L', 'M', 'H')),
    air_temperature_k       DOUBLE PRECISION,
    process_temperature_k   DOUBLE PRECISION,
    rotational_speed_rpm    DOUBLE PRECISION,
    torque_nm               DOUBLE PRECISION,
    tool_wear_min           DOUBLE PRECISION,
    machine_failure         SMALLINT NOT NULL,
    twf                     SMALLINT NOT NULL,
    hdf                     SMALLINT NOT NULL,
    pwf                     SMALLINT NOT NULL,
    osf                     SMALLINT NOT NULL,
    rnf                     SMALLINT NOT NULL
);

-- Only query pattern anticipated for this table is "show me real failure
-- examples of type X" — index the failure flag, not much else needed.
CREATE INDEX idx_ai4i_reference_machine_failure ON ai4i_reference (machine_failure);


-- ---------------------------------------------------------------------
-- tenant_schema_mappings — how a company's raw columns map onto the
-- canonical reading schema (app/onboarding). One active mapping per
-- tenant + dataset kind; the config is validated by
-- app.onboarding.mapping.MappingConfig before it is ever stored.
-- ---------------------------------------------------------------------
CREATE TABLE tenant_schema_mappings (
    id            SERIAL PRIMARY KEY,
    tenant_id     VARCHAR(48) NOT NULL REFERENCES tenants(tenant_id),
    dataset_kind  VARCHAR(30) NOT NULL DEFAULT 'operational' CHECK (dataset_kind IN ('operational', 'maintenance')),
    config        JSONB       NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    UNIQUE (tenant_id, dataset_kind)
);


-- ---------------------------------------------------------------------
-- tenant_settings — per-tenant calibration override (production-
-- readiness fixes 11/12): risk thresholds, RAG coverage floor,
-- machine-ID scheme. No row for a tenant means "use the documented
-- defaults" (app/core/tenant_settings.py) — see migrations/versions/0003.
-- ---------------------------------------------------------------------
CREATE TABLE tenant_settings (
    tenant_id   VARCHAR(48) PRIMARY KEY REFERENCES tenants(tenant_id),
    config      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    updated_at  TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);


-- ---------------------------------------------------------------------
-- investigation_audit_log — one row per successful /investigate or /chat
-- call (production-readiness fix 19): who (tenant + credential state),
-- what machine, what the agent concluded. Append-only.
-- ---------------------------------------------------------------------
CREATE TABLE investigation_audit_log (
    id            BIGSERIAL PRIMARY KEY,
    tenant_id     VARCHAR(48) NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    request_id    VARCHAR(64),
    endpoint      VARCHAR(20) NOT NULL CHECK (endpoint IN ('investigate', 'chat')),
    machine_id    VARCHAR(64),
    intent        VARCHAR(30),
    risk_level    VARCHAR(10),
    authenticated BOOLEAN     NOT NULL,
    question      TEXT        NOT NULL,
    created_at    TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE INDEX idx_investigation_audit_log_tenant_created ON investigation_audit_log (tenant_id, created_at);


-- ---------------------------------------------------------------------
-- ingestion_checkpoints — one row per (tenant, source) recording how far
-- an incremental ingestion run has gotten (production-readiness fix 17;
-- see scripts/incremental_load.py).
-- ---------------------------------------------------------------------
CREATE TABLE ingestion_checkpoints (
    tenant_id        VARCHAR(48) NOT NULL REFERENCES tenants(tenant_id),
    source           VARCHAR(50) NOT NULL,
    last_window_end  TIMESTAMP,
    last_run_at      TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    rows_processed   BIGINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (tenant_id, source)
);


-- ---------------------------------------------------------------------
-- tenant_settings seed for the demo tenant (0005): enables the `ai4i`
-- anomaly rule pack so the AI4I physical rules keep running as before.
-- ---------------------------------------------------------------------
INSERT INTO tenant_settings (tenant_id, config)
VALUES ('default', '{"anomaly": {"rule_packs": {"ai4i": {}}}}'::jsonb)
ON CONFLICT (tenant_id) DO UPDATE
    SET config = tenant_settings.config || EXCLUDED.config;


-- ---------------------------------------------------------------------
-- sensor_registry — per-tenant sensor vocabulary and anomaly rules (0005):
-- unit, normal range, optional per-sensor z-score threshold, enabled flag.
-- Read by app/core/anomaly_rules.py. `enabled = FALSE` means "not evaluated
-- by the generic z-score/range rules" (the demo's temperature/speed sensors
-- only feed the `ai4i` rule pack).
-- ---------------------------------------------------------------------
CREATE TABLE sensor_registry (
    tenant_id          VARCHAR(48)      NOT NULL REFERENCES tenants(tenant_id),
    sensor_name        VARCHAR(64)      NOT NULL CHECK (sensor_name ~ '^[a-z][a-z0-9_]{0,63}$'),
    unit               VARCHAR(32)      NOT NULL,
    normal_min         DOUBLE PRECISION,
    normal_max         DOUBLE PRECISION,
    z_score_threshold  DOUBLE PRECISION CHECK (z_score_threshold > 0),
    enabled            BOOLEAN          NOT NULL DEFAULT TRUE,
    PRIMARY KEY (tenant_id, sensor_name),
    CHECK (normal_min IS NULL OR normal_max IS NULL OR normal_min <= normal_max)
);

INSERT INTO sensor_registry (tenant_id, sensor_name, unit, enabled) VALUES
    ('default', 'torque_nm', 'Nm', TRUE),
    ('default', 'tool_wear_min', 'min', TRUE),
    ('default', 'production_rate', 'units/h', TRUE),
    ('default', 'defect_rate', 'fraction', TRUE),
    ('default', 'energy_consumption_kwh', 'kWh', TRUE),
    ('default', 'air_temperature_k', 'K', FALSE),
    ('default', 'process_temperature_k', 'K', FALSE),
    ('default', 'rotational_speed_rpm', 'rpm', FALSE);


-- ---------------------------------------------------------------------
-- sensor_readings — long-format raw readings (0005). Partitioned by
-- RANGE(ts) with a single DEFAULT partition, same approach and reasoning
-- as sensor_summary/machine_anomalies (0004); scripts/manage_partitions.py
-- adds monthly partitions. The PRIMARY KEY is the idempotency key: loaders
-- INSERT ... ON CONFLICT on it, so re-running a load never duplicates rows.
-- ---------------------------------------------------------------------
CREATE TABLE sensor_readings (
    tenant_id    VARCHAR(48)      NOT NULL,
    machine_id   VARCHAR(64)      NOT NULL,
    sensor_name  VARCHAR(64)      NOT NULL,
    ts           TIMESTAMP        NOT NULL,
    value        DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (tenant_id, machine_id, sensor_name, ts),
    FOREIGN KEY (tenant_id, machine_id) REFERENCES machines (tenant_id, machine_id),
    FOREIGN KEY (tenant_id, sensor_name) REFERENCES sensor_registry (tenant_id, sensor_name)
) PARTITION BY RANGE (ts);

CREATE TABLE sensor_readings_default PARTITION OF sensor_readings DEFAULT;

CREATE INDEX idx_sensor_readings_tenant_ts ON sensor_readings (tenant_id, ts);

-- ---------------------------------------------------------------------
-- Row-level security (0006, Phase 2): tenant isolation enforced by Postgres.
-- Policies compare tenant_id with the transaction-local setting
-- `app.tenant_id` (app/database/tenant_context.py); unset = no rows, writes
-- fail. FORCE applies the policies to the table owner too (superusers and
-- BYPASSRLS roles still bypass). `tenants` and `ai4i_reference` stay outside
-- RLS; the API role (`iia_app`, least privilege, LOGIN set by
-- scripts/provision_app_role.py) reaches `tenants` only via the SECURITY
-- DEFINER auth_lookup_tenant(). iia_enable_tenant_rls() is also called for
-- each partition scripts/manage_partitions.py creates.
-- ---------------------------------------------------------------------
CREATE FUNCTION iia_enable_tenant_rls(tbl regclass) RETURNS void
LANGUAGE plpgsql AS $fn$
BEGIN
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', tbl);
    EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY', tbl);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %s', tbl);
    EXECUTE format($q$CREATE POLICY tenant_isolation ON %s
                       USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')) WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))$q$, tbl);
END
$fn$;

CREATE FUNCTION auth_lookup_tenant(p_hash text)
RETURNS TABLE (tenant_id varchar, name varchar)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
    SELECT t.tenant_id, t.name FROM public.tenants t
    WHERE t.api_key_hash = p_hash AND t.active
$fn$;

CREATE FUNCTION iia_grant_app_privileges() RETURNS void
LANGUAGE plpgsql AS $fn$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'iia_app') THEN
        CREATE ROLE iia_app NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
    END IF;
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM iia_app;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM iia_app;
    GRANT USAGE ON SCHEMA public TO iia_app;
    GRANT SELECT ON machines, sensor_summary, machine_anomalies, maintenance_records,
        sensor_registry, sensor_readings, tenant_settings, ai4i_reference TO iia_app;
    GRANT INSERT ON investigation_audit_log TO iia_app;
    GRANT USAGE ON SEQUENCE investigation_audit_log_id_seq TO iia_app;
    REVOKE ALL ON FUNCTION auth_lookup_tenant(text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION auth_lookup_tenant(text) TO iia_app;
    REVOKE ALL ON FUNCTION iia_enable_tenant_rls(regclass) FROM PUBLIC;
    REVOKE ALL ON FUNCTION iia_grant_app_privileges() FROM PUBLIC;
END
$fn$;

SELECT iia_enable_tenant_rls('machines');
SELECT iia_enable_tenant_rls('sensor_summary');
SELECT iia_enable_tenant_rls('machine_anomalies');
SELECT iia_enable_tenant_rls('maintenance_records');
SELECT iia_enable_tenant_rls('sensor_registry');
SELECT iia_enable_tenant_rls('sensor_readings');
SELECT iia_enable_tenant_rls('tenant_settings');
SELECT iia_enable_tenant_rls('tenant_schema_mappings');
SELECT iia_enable_tenant_rls('investigation_audit_log');
SELECT iia_enable_tenant_rls('ingestion_checkpoints');
SELECT iia_enable_tenant_rls(relid) FROM pg_partition_tree('sensor_summary') WHERE isleaf;
SELECT iia_enable_tenant_rls(relid) FROM pg_partition_tree('machine_anomalies') WHERE isleaf;
SELECT iia_enable_tenant_rls(relid) FROM pg_partition_tree('sensor_readings') WHERE isleaf;
SELECT iia_grant_app_privileges();